services:
  redis:
    container_name: forecast-redis-1
    image: 'redis:latest'
  nginx:
    container_name: forecast-nginx-1
    depends_on:
      - api
      - ui
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
  api:
    container_name: forecast-api-1
    depends_on:
      - redis
    # Allows to attach to the running container and interact with the output (useful for debugging)
    tty: true
    stdin_open: true
    # Passes all specified environment variables to the container
    env_file: '.env'
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  ui:
    container_name: forecast-ui-1
    environment:
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
